apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shipzen-tls-cert
  namespace: shipzen-system
  labels:
    shipzen.jeneeldumasia.codes/system: "true"
spec:
  secretName: shipzen-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.shipzen.jeneeldumasia.codes"
    - "shipzen.jeneeldumasia.codes"
