apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: node-exporter-exception
  namespace: observability
spec:
  exceptions:
  - policyName: "*"
    ruleNames:
    - "*"
  match:
    any:
    - resources:
        kinds:
        - Pod
        - DaemonSet
        namespaces:
        - observability
        names:
        - "*node-exporter*"
