apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shipzen-builder-scaledobject
  namespace: shipzen-build
spec:
  scaleTargetRef:
    name: shipzen-builder
  minReplicaCount: 0 # Scale to zero supported
  maxReplicaCount: 100 # Target max 100 concurrent builds
  cooldownPeriod: 300 # 5 minutes cooldown to prevent thrashing
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.shipzen-system.svc.cluster.local:6379
        stream: builder_queue
        consumerGroup: builder_group
        pendingEntriesCount: "1" # Scale up for every 1 pending build
